# Generated by Django 3.0.9 on 2021-03-30 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('Food', 'food'), ('Clothing', 'clothing'), ('Housing', 'housing'), ('Education', 'education'), ('Entertainment', 'entertainment'), ('Other', 'other')], max_length=20)),
                ('projected', models.CharField(max_length=20)),
                ('actual', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
