# Generated by Django 3.0.9 on 2021-03-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210324_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksentry',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('school', 'School'), ('work', 'Work'), ('self improvement', 'Self improvement'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tasksentry',
            name='completed',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
