# Generated by Django 3.0.9 on 2021-03-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210329_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksentry',
            name='completed',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=3),
        ),
    ]
