# Generated by Django 3.0.9 on 2021-03-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210329_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksentry',
            name='completed',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
